### ISSUE TITLE
undefined method `to_prepare' for ActionDispatch::Reloader:Class (Redmine 4.0 / Rails 5)

### ISSUE THREAD

**Issue by Dmitry-Gal** [RubyClickAP/clipboard_image_paste#1]
Unable to run DB migrations after upgrading to Redmine 4.0.3.stable, which uses Rails 5.2.2.1

$ bundle exec rake redmine:plugins:migrate RAILS_ENV="production"
rake aborted!
NoMethodError: undefined method `to_prepare' for ActionDispatch::Callbacks:Class
Did you mean?  to_param
/var/www/redmine/plugins/clipboard_image_paste/init.rb:32:in `<top (required)>'
/var/www/redmine/lib/redmine/plugin.rb:175:in `block in load'
/var/www/redmine/lib/redmine/plugin.rb:166:in `each'
/var/www/redmine/lib/redmine/plugin.rb:166:in `load'
/var/www/redmine/config/initializers/30-redmine.rb:21:in `<top (required)>'
/var/www/redmine/config/environment.rb:14:in `<top (required)>'
/usr/local/rbenv/versions/2.3.5/bin/bundle:23:in `load'
/usr/local/rbenv/versions/2.3.5/bin/bundle:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

**Comment by Dmitry-Gal** [comment]
I have one more plugin - redmine_lightbox2 with the same method - to_prepare and it works "from the box" without any errors.
